export enum ACTION_TYPE {
  DEFAULT = 'DEFAULT',
  REQUEST_NEW = 'REQUEST_NEW',
  REQUEST_RESOLVE = 'REQUEST_RESOLVE',
  REQUEST_OPEN_CONFIRM = 'REQUEST_OPEN_CONFIRM',
  REQUEST_RESOLVED = 'REQUEST_RESOLVED',
  ENABLE = 'ENABLE',
  ENABLE_DONE = 'ENABLE_DONE'
}
